name: Remote Dispatch Responder

on: [repository_dispatch]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  ping:
    runs-on: ubuntu-24.04
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Fetch code
        run: |
          git clone https://github.com/simwrapper/simwrapper
          cd simwrapper
          git checkout bleeding
          echo "bleeding.simwrapper.app" > public/CNAME
          cd ..
          mv simwrapper/* .

      - name: npm ci
        run: |
          npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          personal_token: ${{ secrets.P_A_T }}
          external_repository: simwrapper/bleeding
          publish_branch: gh-pages
          publish_dir: ./dist
